"""add token_blocklist for JWT revocation

Revision ID: 56e0d1e07c3f
Revises: e4e6cb9cdcda
Create Date: 2026-09-29 23:46:06.434088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e0d1e07c3f'
down_revision = 'e4e6cb9cdcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_blocklist_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_blocklist_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_token_blocklist_jti', ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index('idx_token_blocklist_jti')
        batch_op.drop_index('idx_token_blocklist_expires_at')

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
